name: Automatically Update Lists
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 6"
jobs:
  Update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update Lists
        run: ./update_lists.sh
      - name: Commit Changes
        continue-on-error: true
        run: |
          git config --global user.name 'wiggels+bot'
          git config --global user.email 'wiggels+bot@gmail.com'
          git add .
          git commit -am "automated list update"
          git push
